version: '3'
services:
  web:
    build: .
    ports: 
      - 5000:5000
    volumes:
      - .:/code
      - /home/ken/model_show/models:/models
    environment:
      FLASK_ENV: development    
  redis:
    image: "redis:alpine"